name: SibylleJacobs
favicon: null
layout_spectrum: 0.99359
typography_spectrum: 0.50322
title: In the Matrix
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060606'
    - '#96b1c2'
    - '#7c6b5b'
    - '#22231e'
    - '#425c41'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
