name: SibylleJacobs
favicon: null
layout_spectrum: 1
typography_spectrum: 0.52292
title: In the Matrix
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060606'
    - '#96b1c2'
    - '#7c6b5b'
    - '#22231e'
    - '#425c41'
  brandStrength: 0.625
  lightness: 0.2558750759344548
  saturation: 0.7643039131071419
  rhythmicContrast: 0.07928749127313495
purpose: []
