name: SibylleJacobs
favicon: null
layout_spectrum: 0.99359
typography_spectrum: 0.50322
title: In the Matrix
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#add6f8'
    - '#83b6e2'
    - '#313d50'
    - '#526670'
    - '#8592a5'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
